// src/pages/index.tsx
import React, { useEffect, useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import path from 'path';

import users from '../data/users.json';
// import allPosts from '../data/allPosts.json';

const inter = Inter({ subsets: ['latin'] });

type PostWithUserInfo = {
  company_name: string;
  desc: string;
  date: string;
  time: string;
  userInfo: {
    _id: number;
    email: string;
    first_name: string;
    last_name: string;
  };
};

export default function Home() {
  console.log("Home");

  useEffect(() => {
    //place all users into 'allPosts'
    const allPosts: PostWithUserInfo[] = [];
    let id: number = 1;
    users.forEach(user => {
      user.posts.forEach(post => {
        // console.log(post);
        const postWithUserInfo = {
          ...post,
          id: id,
          userInfo: {
            _id: user._id,
            email: user.email,
            first_name: user.first_name,
            last_name: user.last_name
          }
        };
        allPosts.push(postWithUserInfo);
        id++;
      });
    });

    const allPostsJSON = JSON.stringify(allPosts, null, 2);

    // console.log(allPostsJSON);

    appendData(allPostsJSON);
    console.log("useEffect");
  }, []);

  async function appendData(data: string) {
    const filePath = path.join(process.cwd(), 'data', 'allPosts.json');

    console.log(filePath);

    const response = await fetch('/api/appendToFile', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ data, filePath })
    });
  
    if (response.ok) {
      console.log('Data appended to file');
    } else {
      console.error('An error occurred');
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* ${styles.main} ${inter.className} */}
      <main className={``}>
        <h2>Main</h2>
      </main>
    </>
  )
}


{/* <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div> */}