// src/pages/index.tsx
import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Router from 'next/router';
// import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import path from 'path';
import { User, Post } from '../types/types';

import users from '../data/users.json';
// import allPosts from '../data/allPosts.json';

// import { PostWithUserInfo } from '../types/types';

import generateData from '../utils/generateData';

import usersToPosts from '@/utils/usersToPosts';

import currentUser from '../data/currentUser.json';

// const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  // console.log("Home");

  useEffect(() => {
    //generate data
    let users = generateData(3, 2, 2);
    const usersJSON = JSON.stringify(users, null, 2);

    //place all posts into 'allPosts'
    let allPosts = usersToPosts(users);
    const postsJSON = JSON.stringify(allPosts, null, 2);

    // console.log(allPostsJSON);

    let currentUser: User = {
      ...users[0],
      id: ""
    }
    const currentUserJSON = JSON.stringify(currentUser, null, 2);

    let currentPost: Post = {
      ...users[0].posts[0],
      postId: ""
    }
    const currentPostJSON = JSON.stringify(currentPost, null, 2);

    appendData(usersJSON, postsJSON, currentUserJSON, currentPostJSON);
    // console.log("useEffect");

    if (currentUser.id === "") {
      Router.push('/About');
    } else {
      Router.push('/UserPage');
    }
  }, []);

  async function appendData(users: string, posts: string, currentUser: string, currentPost: string) {
    // console.log("in index/appendData");
    // console.log(data.length);
    const usersResponse = await fetch('/api/appendToFile', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ data: users, fileName: "users" })
    });
    // console.log("index/appendData", usersResponse);

    const currentUserResponse = await fetch('/api/appendToFile', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ data: currentUser, fileName: "currentUser" })
    });
    // console.log("index/appendData", postsResponse);

    const currentPostResponse = await fetch('/api/appendToFile', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ data: currentPost, fileName: "currentPost" })
    });
    // console.log("index/appendData", currentPostResponse);

    const postsResponse = await fetch('/api/appendToFile', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ data: posts, fileName: "posts" })
    });
    // console.log("index/appendData", currentPostResponse);
  
    if (usersResponse.ok && currentUserResponse.ok && currentPostResponse.ok && postsResponse.ok) {
      console.log('Data appended to file');
    } else {
      console.error('An error occurred');
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* ${styles.main} ${inter.className} */}
      <main className={``}>
        <h2>Main</h2>
      </main>
    </>
  )
}